### ISSUE TITLE
Console notifications

### ISSUE THREAD

**Issue by DieterKoblenz** [ray73864/aspace#5]
Console notifications are not working properly. The function "consolenotify" and "consolenotifyall" are present in the compiled functions and respond when not given the right arguments however the commands themselves don't work.

**Comment by mike347** [comment]
Sounds like you didn't update your console list and run @space/consoles. See the main wiki page:https://github.com/ray73864/aspace/wiki

**Comment by DieterKoblenz** [comment]
Hi, 

Actually I did this! Consoles do work (for example I can activate systems, and I get an error while activating sensors when my ship isn't equiped with them). So all the "sdb" things work.

**Comment by mike347** [comment]
Those will work because they work off by grabbing your dbref directly off of the console and sending it to you directly, if notifications aren't working then usually it's due to the consoles not being setup properly. Try setting one manually by doing this: [sdb(var,console,fighter,dbref)] where dbref is the dbref of your fighter console, make sure your console is in fighter mode and do an sdb(r,dbref#) on it to force it to refresh sensor contacts. See if it works then.

**Comment by DieterKoblenz** [comment]
Not sure if I got it completely but:

First I did: th [sdb(var,console,fighter,#35)] (where #35 is console 1, which I man and is in fighter mode)
Second I did: th sdb(r,#33) (where #33 is my ship) it returns "1"

**Comment by mike347** [comment]
Now test whatever notification wasn't working previously and see if it works?

**Comment by DieterKoblenz** [comment]
Checked this:
For example "main 100" I would expect [Wiz]--[M/A reactor set at 100%], but it doesn't.

Neither does "th consolenotifyall(3, hi)"

**Comment by mike347** [comment]
Is tiny math @config option turned on?

**Comment by DieterKoblenz** [comment]
tiny_math                                Yes

**Comment by mike347** [comment]
Ultimate issue was &CONSOLES not being properly set on the space object. All fixed :)
